CREATE DATABASE DB_MECANICO

GO

USE [DB_MECANICO]

GO

CREATE TABLE TB_CLIENTE (
	COD_CLIENTE			INT IDENTITY(1, 1) PRIMARY KEY,
	NOME_CLIENTE		VARCHAR(100) NOT NULL,
	EMAIL_CLIENTE		VARCHAR(50) NULL,
	CELULAR_CLIENTE		VARCHAR(15) NULL,
	TELEFONE_CLIENTE	VARCHAR(14) NULL,
	DATA_NASC_CLIENTE	varchar(50) NULL
)

GO

CREATE TABLE TB_MARCA (
	COD_MARCA	INT IDENTITY(1, 1) PRIMARY KEY,
	DESC_MARCA	VARCHAR(100) NOT NULL
)

GO

CREATE TABLE TB_VEICULO (
	COD_VEICULO		INT IDENTITY(1, 1) PRIMARY KEY,
	COD_CLIENTE		INT FOREIGN KEY REFERENCES TB_CLIENTE (COD_CLIENTE),
	COD_MARCA		INT	FOREIGN KEY REFERENCES TB_MARCA (COD_MARCA),
	DESC_MODELO		VARCHAR(300) NOT NULL,
	DATA_CONSERTO	varchar(50) NULL,
	ANO_FABRICADO	INT NULL,
	ANO_MODELO		INT NULL
)

GO

CREATE TABLE TB_FUNCIONARIO (
	COD_FUNCIONARIO			INT IDENTITY(1, 1) PRIMARY KEY,
	NOME_FUNCIONARIO		VARCHAR(100) NOT NULL,
	EMAIL_FUNCIONARIO		VARCHAR(50) NULL,
	CPF_FUNCIONARIO			VARCHAR(15) NOT NULL,
	CELULAR_FUNCIONARIO		VARCHAR(15) NULL,
	TELEFONE_FUNCIONARIO	VARCHAR(14) NULL,
	DATA_NASC_FUNCIONARIO	varchar(50) NULL,
	CIDADE_FUNCIONARIO		VARCHAR(100) NULL,
	ESTADO_FUNCIONARIO		VARCHAR(50) NULL,
	BAIRRO_FUNCIONARIO		VARCHAR(50) NULL,
	ENDERECO_FUNCIONARIO	VARCHAR(150) NULL,
	NUMERO_END_FUNCIONARIO	INT NULL,
	SALARIO_FUNCIONARIO		NUMERIC(8,2) NOT NULL
)

GO

CREATE TABLE TB_PAIS (
	COD_PAIS	INT IDENTITY(1, 1) PRIMARY KEY,
	DESC_PAIS	VARCHAR(300) NOT NULL
)

GO

CREATE TABLE TB_FORNECEDOR (
	COD_FORNECEDOR			INT IDENTITY(1, 1) PRIMARY KEY,
	NOME_FORNECEDOR			VARCHAR(100) NOT NULL,
	EMAIL_FORNECEDOR		VARCHAR(50) NULL,
	CNPJ_FORNECEDOR			VARCHAR(15) NOT NULL,
	CELULAR_FORNECEDOR		VARCHAR(15) NULL,
	TELEFONE_FORNECEDOR		VARCHAR(14) NULL,
	COD_PAIS				INT	FOREIGN KEY REFERENCES TB_PAIS (COD_PAIS),
	CIDADE_FORNECEDOR		VARCHAR(100) NULL,
	ESTADO_FORNECEDOR		VARCHAR(50) NULL,
	BAIRRO_FORNECEDOR		VARCHAR(50) NULL,
	ENDERECO_FORNECEDOR		VARCHAR(150) NULL,
	NUMERO_END_FORNECEDOR	INT NULL
)

GO

CREATE TABLE TB_FERRAMENTA (
	COD_FERRAMENTA			INT IDENTITY(1, 1) PRIMARY KEY,
	COD_FORNECEDOR			INT FOREIGN KEY REFERENCES TB_FORNECEDOR (COD_FORNECEDOR),
	NOME_FERRAMENTA			VARCHAR(100) NOT NULL,
	DATA_COMPRADA			varchar(50) NULL,
	GARANTIA_FERRAMENTA		NUMERIC(6, 2) NULL,
	VALOR_FERRAMENTA		NUMERIC(8, 2) NULL,
	MARCA_FERRAMENTA		VARCHAR(100) NULL
)

GO

CREATE TABLE TB_PECA (
	COD_PECA		INT IDENTITY(1, 1) PRIMARY KEY,
	COD_FORNECEDOR	INT FOREIGN KEY REFERENCES TB_FORNECEDOR (COD_FORNECEDOR),
	NOME_PECA		VARCHAR(100) NOT NULL,
	DATA_COMPRADA	varchar(50) NULL,
	GARANTIA_PECA	NUMERIC(6, 2) NULL,
	VALOR_PECA		NUMERIC(8, 2) NULL,
	MARCA_PECA		VARCHAR(100) NULL
)

GO

CREATE TABLE TB_PEDIDO (
	COD_PEDIDO		INT IDENTITY(1, 1) PRIMARY KEY,
	DATA_PEDIDO		DATE NOT NULL,
	DATA_FINALIZADO	varchar(50) NULL,
	CUSTO_PEDIDO	NUMERIC(8, 2) NULL,
	VALOR_PEDIDO	NUMERIC(8, 2) NULL,
	HORAS_PEDIDO	NUMERIC(5, 2) NULL,
	PEDIDO_PAGO		INT NULL,
	COD_CLIENTE		INT FOREIGN KEY REFERENCES TB_CLIENTE (COD_CLIENTE) NOT NULL,
	COD_VEICULO		INT FOREIGN KEY REFERENCES TB_VEICULO (COD_VEICULO) NOT NULL
)

GO

CREATE TABLE TB_SERVICO (
	COD_SERVICO		INT IDENTITY(1, 1) PRIMARY KEY,
	NOME_SERVICO	VARCHAR(100) NOT NULL,
	CUSTO_SERVICO	NUMERIC(8, 2) NULL,
	VALOR_SERVICO	NUMERIC(8, 2) NULL,
	HORAS_SERVICO	NUMERIC(8, 2) NULL
)

GO

CREATE TABLE TB_FUNCIONARIO_SERVICO (
	COD_SERVICO			INT FOREIGN KEY REFERENCES TB_SERVICO (COD_SERVICO) NOT NULL,
	COD_FUNCIONARIO		INT FOREIGN KEY REFERENCES TB_FUNCIONARIO (COD_FUNCIONARIO) NOT NULL,
	PRIMARY KEY (COD_SERVICO, COD_FUNCIONARIO)
)

GO

CREATE TABLE TB_FERRAMENTA_SERVICO (
	COD_SERVICO			INT FOREIGN KEY REFERENCES TB_SERVICO (COD_SERVICO) NOT NULL,
	COD_FERRAMENTA		INT FOREIGN KEY REFERENCES TB_FERRAMENTA (COD_FERRAMENTA) NOT NULL,
	PRIMARY KEY (COD_SERVICO, COD_FERRAMENTA)
)

GO

CREATE TABLE TB_PECA_SERVICO (
	COD_SERVICO	INT FOREIGN KEY REFERENCES TB_SERVICO (COD_SERVICO) NOT NULL,
	COD_PECA	INT FOREIGN KEY REFERENCES TB_PECA (COD_PECA) NOT NULL,
	PRIMARY KEY (COD_SERVICO, COD_PECA)
)

GO

CREATE TABLE TB_SERVICO_PEDIDO (
	COD_SERVICO		INT FOREIGN KEY REFERENCES TB_SERVICO (COD_SERVICO) NOT NULL,
	COD_PEDIDO		INT FOREIGN KEY REFERENCES TB_PEDIDO (COD_PEDIDO) NOT NULL,
	PRIMARY KEY (COD_SERVICO, COD_PEDIDO)
)

GO
